[package]
name = "fuzz-targets-exec-all"
version = "0.1.0"
authors = ["Patrick Ventuzelo <ventuzelo.patrick@gmail.com>"]
edition = "2018"

[dependencies]
colored = "1.9"
fuzz-targets = {path = "../targets"}
