[package]
name = "fuzz-targets"
version = "0.1.0"
authors = ["Patrick Ventuzelo <ventuzelo.patrick@gmail.com>"]
edition = "2018"

[dependencies]
wasmi = "0.6"
wasmi-validation = "0.3"
parity-wasm = "0.41"
wasmer-runtime = "0.16"
wasmer-singlepass-backend = "0.16"
wasmtime = "0.15"
lightbeam = "0.15"
wasmparser = "0.51"
binaryen = "0.10"
wabt = "0.9"
wasmprinter = "0.2.5"
wasm3 = "0.1.1"

